### ISSUE TITLE
Errors when launching on OSX

### ISSUE THREAD

**Issue by dmnc** [vacaboja/tg#6]
> WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

and 

> WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

I'm guessing the second is a GTK+2/3 issue as I believe gtk+3 does not use carbon. The first one, I am completely lost on - it looks like it's probably from somewhere up the dependency tree to me.

**Comment by vacaboja** [comment]
Hi, thanks.

The first warning is most probably caused by gtk2. It shouldn't be serious, and it will go away either when they fix it, or when tg switches to something more modern.

The second warning comes from portaudio. The portaudio developers are aware of this issue, and they decided to keep using the deprecated API to support older versions of OS X. They will probably switch to a more recent API when they see it fit (https://app.assembla.com/spaces/portaudio/tickets/243-portaudio-support-for-os-x-10-11-el-capitan/details#).

I will keep an eye on these issues, thanks again.
